### ISSUE TITLE
"Transaction execution error" for takeOrderFromFund

### ISSUE THREAD

**Issue by schmidsi** [melonproject/melon.js#56]
Running the integration tests, they always fail at gasEstimating of Fund.takeOrder with "Transaction execution error".

This leads to the assumption, that something fails inside the protocol around here: 
https://github.com/melonproject/protocol/blob/0.3.6-alpha.2/contracts/Fund.sol#L548-L594

If not estimating gas and directly call takeOrder with the highest gas possible like this:
```
const transaction = await fundContract.takeOrder(...args, {
      from,
      gas: 6986000,
    });
```

It runs through but without any logs:
![Integrationtest logs](https://user-images.githubusercontent.com/103280/31012993-4d86c078-a514-11e7-8209-eefd824c26db.png)

This indicates again, that something fails inside the protocol above.

Furthermore, as talked with @jennazenk, a similar error arises from MetaMask in the decentralised-portal if trying to take an order without the possibility to sign the transaction. Metamask tries to estimate gas before each call and this estimation fails also.

The next steps would be 
- [x] Try to take an order from the orderbook
- [x] ensure the assumptions made in [Fund.takeOrder](https://github.com/melonproject/protocol/blob/0.3.6-alpha.2/contracts/Fund.sol#L548-L594) manually (e.g. module.riskmgmt.isTakePermitted) like [in subscribe](https://github.com/melonproject/melon.js/blob/0.3/lib/participation/transactions/subscribe.js#L36-L47)

**Comment by jennazenk** [comment]
Thanks Simon for your input. 

On my end, I was able several times to take an order from a fund both from Melon.js (branch 0.3) and from the decentralized-portal. From orderbook and from regular account.

However, takeOrderFromFund  fails sometimes for no identified reason. Suspected until now that it was a gas related issue. It is hard for me to do more tests on d-portal right now because Metamask just updated to v3.10.1 and it seems a bit buggy atm.
